-- AlterTable: SME
ALTER TABLE "SME" ALTER COLUMN "smeID" TYPE VARCHAR(36);
ALTER TABLE "SME" ALTER COLUMN "businessName" TYPE VARCHAR(150);
ALTER TABLE "SME" ALTER COLUMN "rcNumber" TYPE VARCHAR(10);
ALTER TABLE "SME" ALTER COLUMN "email" TYPE VARCHAR(255);
ALTER TABLE "SME" ALTER COLUMN "passwordHash" TYPE VARCHAR(60);
ALTER TABLE "SME" ALTER COLUMN "businessAddress" TYPE VARCHAR(255);
ALTER TABLE "SME" ALTER COLUMN "businessState" TYPE VARCHAR(50);

-- AlterTable: Product
ALTER TABLE "Product" ALTER COLUMN "productID" TYPE VARCHAR(36);
ALTER TABLE "Product" ALTER COLUMN "smeID" TYPE VARCHAR(36);
ALTER TABLE "Product" ALTER COLUMN "productName" TYPE VARCHAR(150);
ALTER TABLE "Product" ALTER COLUMN "category" TYPE VARCHAR(50);

-- AlterTable: ParentQRCode
ALTER TABLE "ParentQRCode" ALTER COLUMN "parentQRID" TYPE VARCHAR(36);
ALTER TABLE "ParentQRCode" ALTER COLUMN "productID" TYPE VARCHAR(36);
ALTER TABLE "ParentQRCode" ALTER COLUMN "qrData" TYPE VARCHAR(70);
ALTER TABLE "ParentQRCode" ALTER COLUMN "genesisTxHash" TYPE VARCHAR(88);

-- AlterTable: ChildQRCode
ALTER TABLE "ChildQRCode" ALTER COLUMN "childQRID" TYPE VARCHAR(36);
ALTER TABLE "ChildQRCode" ALTER COLUMN "parentQRID" TYPE VARCHAR(36);
ALTER TABLE "ChildQRCode" ALTER COLUMN "qrData" TYPE VARCHAR(70);

-- AlterTable: ScanEvent
ALTER TABLE "ScanEvent" ALTER COLUMN "scanID" TYPE VARCHAR(36);
ALTER TABLE "ScanEvent" ALTER COLUMN "parentQRID" TYPE VARCHAR(36);
ALTER TABLE "ScanEvent" ALTER COLUMN "scannerRole" TYPE VARCHAR(20);
ALTER TABLE "ScanEvent" ALTER COLUMN "gpsLocation" TYPE VARCHAR(150);
ALTER TABLE "ScanEvent" ALTER COLUMN "txHash" TYPE VARCHAR(88);

-- AlterTable: HandoffCode
ALTER TABLE "HandoffCode" ALTER COLUMN "codeID" TYPE VARCHAR(36);
ALTER TABLE "HandoffCode" ALTER COLUMN "scanID" TYPE VARCHAR(36);
ALTER TABLE "HandoffCode" ALTER COLUMN "codeValue" TYPE VARCHAR(4);

-- AlterTable: AuthToken
ALTER TABLE "AuthToken" ALTER COLUMN "id" TYPE VARCHAR(36);
ALTER TABLE "AuthToken" ALTER COLUMN "smeID" TYPE VARCHAR(36);
ALTER TABLE "AuthToken" ALTER COLUMN "token" TYPE VARCHAR(36);
