/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./layout/**/*.html",
    "./layout/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#080708",
        surface: "#111111",
        "surface-2": "#1A1A1A",
        "surface-elevated": "#272a31",
        "surface-light": "#32353c",
        green: "#D6FFB7",
        blue: "#3185FC",
        "blue-dark": "#1E4D99",
        muted: "#77867F",
        danger: "#FF6B6B",
        warning: "#FFAA00",
        border: "rgba(119,134,127,0.15)",
        "border-light": "rgba(119,134,127,0.25)",
        "text-primary": "#E0E2EC",
        "text-secondary": "#C1C6D6",
        "text-muted": "#77867F",
        "outline-variant": "#414754",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        display: ["Noto Serif", "serif"],
        body: ["Space Grotesk", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "hero-headline": ["Noto Serif", "serif"],
        "hero-italic": ["Noto Serif", "serif"],
        "section-heading": ["Noto Serif", "serif"],
        "card-title": ["Space Grotesk", "sans-serif"],
        "technical-data": ["JetBrains Mono", "monospace"],
        "metric-large": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "chip-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "hero-headline": ["60px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "hero-italic": ["60px", { lineHeight: "1.1", fontWeight: "500" }],
        "section-heading": ["36px", { lineHeight: "1.2", fontWeight: "500" }],
        "card-title": ["17px", { lineHeight: "1.4", fontWeight: "500" }],
        "technical-data": ["11px", { lineHeight: "1.2", fontWeight: "400" }],
        "metric-large": ["32px", { lineHeight: "1", fontWeight: "500" }],
        "label-caps": ["11px", { letterSpacing: "0.1em", fontWeight: "500" }],
        "chip-mono": ["10px", { lineHeight: "1", fontWeight: "500" }],
        body: ["15px", { lineHeight: "1.7", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
